@startuml

!include ./../ContextManagerClassDiagram.puml

namespace e5 {
    class SerialPrinter {
        - const AsyncTcp::ContextManagerPtr & m_ctx
        --
        + SerialPrinter(const AsyncTcp::ContextManagerPtr& ctx)
        + uint32_t print(std::unique_ptr<std::string> message)
    }
}

e5::SerialPrinter --> AsyncTcp::ContextManager : uses

@enduml
